swagger: '2.0'

# This is your document metadata
info:
  version: "2.0.0"
  title: Conapp 2

paths:
  /register:
    parameters:
      - name: oAuthToken
        in: formData
        type: string
        description: Twitter OAuth token
        required: true
      - name: oAuthTokenSecret
        in: formData
        type: string
        description: Twitter OAuth token secret
        required: true
    post: # or put?
      responses:
        200:
          description: Successfully logged in
          schema:
            type: string
            format: uuid
            description: API key for this specific installation to use to communicate with Conapp
        401:
          description: Authentication failed

  /fcm:
    put:
      description: Register an installation's FCM registration ID
      parameters:
        - name: registrationId
          in: body
          required: true
          schema:
            type: string
      responses:
        200:
          description: Registration ID successfully stored

  /apns:
    put:
      description: Register an installation's APNs device token
      parameters:
        - name: deviceToken
          in: body
          required: true
          schema:
            type: string
            format: bytes
      responses:
        200:
          description: Device token successfully stored

  /location/:
    get:
      description: |
        Retrieves the latest location of each user this user follows
      responses:
        200:
          description: Locations successfully retrieved
          schema:
            title: Locations
            type: array
            items:
              $ref: '#/definitions/Location'
    put:
      description: Updates the current location of the user
      responses:
        200:
          description: Location successfully stored
        429:
          description: Location was already updated too recently
    delete:
      description: Hides the user's current location
      responses:
        200:
          description: Location successfully hidden

definitions:
  Location:
    type: object
    required:
      - id
      - location
      - timestamp
      - username
    properties:
      id:
        type: integer
      location:
        type: string
        description: The user's location as entered by the user
        example: Conference room B
      timestamp:
        type: string
        format: date-time
      displayTimestamp:
        type: string
        description: |
          The time at which the location was updated, humanely formatted for presentation to the user. For example, this may be "four minutes ago".
      username:
        type: string
      profilePhoto:
        type: string
        format: url
      conference:
        type: string
        description: The hashtag representing a conference
        example: '#oow16'
