swagger: '2.0'

info:
  version: "2.0.0"
  title: Conapp 2

consumes:
  - application/json

produces:
  - application/json

paths:
  /session:
    put:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RegistrationDetails'
      responses:
        200:
          description: Successfully logged in
          schema:
            type: object
            properties:
              apiKey:
                type: string
                format: uuid
                description: API key for this specific installation to use to communicate with Conapp
        401:
          description: Authentication failed
    delete:
      responses:
        204:
          description: Successfully logged out

  /notification:
    put:
      description: Turn on push notifications
      responses:
        204:
          description: Push notifications enabled
    delete:
      description: Turn off push notifications
      responses:
        204:
          description: Push notifications disabled

  /fcm/registrationId:
    put:
      description: Register an installation's FCM registration ID
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              registrationId:
                type: string
      responses:
        204:
          description: Registration ID successfully stored

  /apns/token:
    put:
      description: Register an installation's APNs device token
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              deviceToken:
                type: string
                format: bytes
      responses:
        204:
          description: Device token successfully stored

  /locations/:
    get:
      description: Retrieve the latest location of each user this user follows
      parameters:
        - name: conference
          in: query
          type: string
          required: false
          description: The conference of interest to the user. If this is specified, only locations from that conference are returned.
      responses:
        200:
          description: Locations successfully retrieved
          schema:
            title: Locations
            type: array
            items:
              $ref: '#/definitions/Location'
    post: # TODO: dedupe with PUT /locations/mine
      description: Update the current location of the user
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              location:
                type: string
      responses:
        200:
          description: Location successfully stored
        429:
          description: Location was already updated too recently

  /locations/mine:
    put:
      description: Update the current location of the user
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              location:
                type: string
      responses:
        200:
          description: Location successfully stored
        429:
          description: Location was already updated too recently
    delete:
      description: Hides the user's current location
      responses:
        200:
          description: Location successfully hidden

  /conference:
    put:
      description: Set the conference of interest for this user. Only updates from this conference will notify the user.
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              conference:
                type: string
      responses:
        204:
          description: The conference was set successfully
    delete:
      description: Clear the conference of interest for this user. The user will be notified about all location updates of their followers.
      responses:
        204:
          description: The conference was successfully cleared

definitions:
  Location:
    type: object
    required:
      - id
      - location
      - timestamp
      - username
    properties:
      id:
        type: integer
      location:
        type: string
        description: The user's location as entered by the user
        example: Conference room B
      timestamp:
        type: string
        format: date-time
      displayTimestamp:
        type: string
        description: |
          The time at which the location was updated, humanely formatted for presentation to the user. For example, this may be "four minutes ago".
      username:
        type: string
      profilePhoto:
        type: string
        format: url
      conference:
        type: string
        description: The hashtag representing a conference
        example: '#oow16'
  RegistrationDetails:
    type: object
    required:
      - oAuthToken
      - oAuthTokenSecret
    properties:
      oAuthToken:
        type: string
        description: Twitter OAuth token
      oAuthTokenSecret:
        type: string
        description: Twitter OAuth token secret
      installationId:
        type: string
        format: uuid
        description: An ID generated by the client for this specific installation of the Conapp app.
